version: "3"
services:

  nodejs_service:
    build: ./nodejs_service
    container_name: nodejs_service_containerS
    ports:
      - "6002:6002"
    networks:
      - library-app
    links:
      - chapters_db
    restart: on-failure
    depends_on:
      - chapters_db
    volumes:
      - ./nodejs_service:/app
      - /app/node_modules
  books_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27018:27017"
    networks:
      - library-app
    volumes:
      - books-volume:/data/db

  chapters_service:
    build: ./chapters_service
    container_name: chapters_service_container
    ports:
      - "5003:5003"
    networks:
      - library-app
    links:
      - chapters_db
    restart: on-failure
    depends_on:
      - chapters_db
    volumes:
      - ./chapters_service:/app
      - /app/node_modules
  chapters_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27019:27017"
    networks:
      - library-app
    volumes:
      - chapters-volume:/data/db
  
  discount_service_node.js:
    build: ./discount_service_node.js
    container_name: discount_service_node.js_container
    ports:
      - "6003:6003"
    networks:
      - library-app
    links:
      - discount_db
    restart: on-failure
    depends_on:
      - discount_db
    volumes:
      - ./discount_service_node.js:/app
      - /app/node_modules
  discount_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27015:27017"
    networks:
      - library-app
    volumes:
      - discount-volume:/data/db

networks:
  library-app:
    driver: bridge
volumes:
  books-volume:
    driver: local
  chapters-volume:
    driver: local
  discount-volume :
    driver : local
  
  
