version: "3"
services:
  books_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - library-app
    volumes:
      - books-volume:/data/db
  nodejs_service:
    build: ./nodejs_service
    container_name: nodejs_service_containerS
    ports:
      - "6002:6002"
    networks:
      - library-app
    links:
      - books_db
    restart : on-failure
    depends_on:
      - books_db
    volumes:
      - ./nodejs_service:/app
      - /app/node_modules
  chapters_service:
    build: ./chapters_service
    container_name: chapters_service_container
    ports:
      - "5002:5002"
    networks:
      - library-app
    links:
      - chapters_db
    restart: on-failure
    depends_on:
      - chapters_db
    volumes:
      - ./chapters_service:/app
      - /app/node_modules
  chapters_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27018:27017"
    networks:
      - library-app
    volumes:
      - chapters-volume:/data/db
networks:
  library-app:
    driver: bridge
volumes:
  chapters-volume:
    driver: local
  books-volume:
    driver: local
