version: "3"
services:
  books_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27018:27017"
    networks:
      - library-app
    volumes:
      - books-volume:/data/db
  nodejs_service:
    build: ./nodejs_service
    container_name: nodejs_service_containerS
    ports:
      - "6002:6002"
    networks:
      - library-app
    depends_on:
      - books_db
    volumes:
      - ./nodejs_service:/app
      - /app/node_modules
networks:
  library-app:
    driver: bridge
volumes:
  books-volume:
    driver: local
